language: python
python:
  - "3.5"
  - "3.6"
install:
  - git clone https://github.com/kute/eventor eventor
  - cd eventor
  - python3 setup.py install
  - pip3 install -r requirements.txt
script:
  - cd test
  - python3 -m unittest discover
branches:
  only:
  - master
notifications:
  email:
      recipients:
        - kutekute00@gmail.com
      on_success: never
      on_failure: always